Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2022-12, with the labels that each got.

#430 Version bump 2.4.1
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  opensearch_dashboards.json
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.4

#429 [Bugfix] filter data streams from rollover alias requirement
  public/pages/Indices/components/ApplyPolicyModal/ApplyPolicyModal.tsx
Labels: backport 2.x

#435 [1.3] Add windows os for unit tests
  .github/workflows/unit-tests-workflow.yml
  package.json
  public/pages/CreateTransform/components/TransformIndices/TransformIndices.tsx
Labels: backport 1.x
