Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2022-11, with the labels that each got.

#315 Complete snapshot restore, mvp for 2.4
  cypress/integration/snapshots_spec.js
  public/models/interfaces.ts
  public/pages/Snapshots/components/ErrorModal/ErrorModal.tsx
  public/pages/Snapshots/components/ErrorModal/index.ts
  public/pages/Snapshots/components/IndexList/IndexList.tsx
  public/pages/Snapshots/components/RenameInput/RenameInput.test.tsx
  public/pages/Snapshots/components/RenameInput/RenameInput.tsx
  public/pages/Snapshots/components/RenameInput/__snapshots__/RenameInput.test.tsx.snap
  public/pages/Snapshots/components/RestoreActivitiesPanel/RestoreActivitiesPanel.tsx
  public/pages/Snapshots/components/RestoreSnapshotFlyout/RestoreSnapshotFlyout.tsx
  public/pages/Snapshots/components/SnapshotRenameOptions/SnapshotRenameOptions.tsx
  public/pages/Snapshots/components/SnapshotRenameOptions/__snapshots__/SnapshotRenameOptions.test.tsx.snap
  public/pages/Snapshots/components/SnapshotRestoreAdvancedOptions/SnapshotRestoreAdvancedOptions.tsx
  public/pages/Snapshots/components/SnapshotRestoreOption/SnapshotRestoreOption.tsx
  public/pages/Snapshots/components/SnapshotRestoreOption/__snapshots__/SnapshotRestoreOption.test.tsx.snap
  public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
  public/pages/Snapshots/helper.tsx
  public/services/IndexService.ts
  public/services/SnapshotManagementService.ts
  server/models/interfaces.ts
  server/services/SnapshotManagementService.ts
Labels: backport 2.x

#325 Add windows mac OS in CI
  .github/workflows/unit-tests-workflow.yml
  package.json
  public/pages/CreateTransform/components/TransformIndices/TransformIndices.tsx
Labels: backport 2.x, backport 2.4

#343 Minor bugfix to Restore Activities panel
  public/pages/Snapshots/components/RestoreActivitiesPanel/RestoreActivitiesPanel.tsx
Labels: backport 2.x, backport 2.4

#353 Feature/extra status
  cypress/integration/indices_spec.js
  models/interfaces.ts
  public/components/CustomFormRow/index.tsx
  public/components/FormGenerator/FormGenerator.test.tsx
  public/components/FormGenerator/__snapshots__/FormGenerator.test.tsx.snap
  public/components/FormGenerator/built_in_components/index.tsx
  public/components/FormGenerator/index.tsx
  public/pages/CreateIndex/containers/CreateIndex/CreateIndex.tsx
  public/pages/Indices/containers/IndexDetail/index.tsx
  public/pages/Indices/containers/Indices/Indices.tsx
  public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
  public/pages/Indices/containers/IndicesActions/index.tsx
  public/pages/Indices/utils/constants.tsx
  server/models/interfaces.ts
  server/services/IndexService.ts
Labels: v2.5.0, index-operation

#365 Change help text in "RestoreSnapshotAdvancedSettings" , documentation url in "IndexSettingsInput"
  public/pages/Snapshots/components/IndexSettingsInput/IndexSettingsInput.tsx
  public/pages/Snapshots/components/SnapshotRestoreAdvancedOptions/SnapshotRestoreAdvancedOptions.tsx
  public/utils/constants.ts
Labels: backport 2.x, backport 2.4

#378 Index operation
  cypress/integration/split_index.js
  package.json
  public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.test.tsx
  public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.tsx
  public/pages/Indices/components/SplitIndexFlyout/__snapshots__/SplitIndexFlyout.test.tsx.snap
  public/pages/Indices/containers/IndicesActions/index.tsx
  yarn.lock
Labels: v2.5.0, index-operation

#391 Index operation
  cypress/integration/split_index.js
  public/pages/CreateIndex/components/AliasSelect/index.tsx
  public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.test.tsx
  public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.tsx
  public/pages/Indices/components/SplitIndexFlyout/__snapshots__/SplitIndexFlyout.test.tsx.snap
  public/pages/Indices/containers/IndicesActions/index.tsx
Labels: v2.5.0, index-operation

#395 Refactor reindex page
  cypress/integration/indices_spec.js
  cypress/integration/reindex_spec.js
  cypress/support/commands.js
  cypress/support/index.d.ts
  public/components/AdvancedSettings/index.tsx
  public/components/FormGenerator/index.tsx
  public/components/Toast/Toast.test.tsx
  public/components/Toast/__snapshots__/Toast.test.tsx.snap
  public/components/Toast/index.tsx
  public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
  public/pages/CreateIndex/containers/IndexForm/index.tsx
  public/pages/CreateIndex/utils/constants.ts
  public/pages/Indices/components/ReindexAdvancedOptions/ReindexAdvancedOptions.test.tsx
  public/pages/Indices/components/ReindexAdvancedOptions/ReindexAdvancedOptions.tsx
  public/pages/Indices/components/ReindexFlyout/ReindexFlyout.test.tsx
  public/pages/Indices/components/ReindexFlyout/ReindexFlyout.tsx
  public/pages/Indices/components/ReindexFlyout/__snapshots__/ReindexFlyout.test.tsx.snap
  public/pages/Indices/containers/Indices/Indices.tsx
  public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
  public/pages/Indices/containers/IndicesActions/index.tsx
  public/pages/Indices/models/interfaces.ts
  public/pages/Main/Main.tsx
  public/pages/Reindex/components/CreateIndexFlyout/CreateIndexFlyout.test.tsx
  public/pages/Reindex/components/CreateIndexFlyout/CreateIndexFlyout.tsx
  public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
  public/pages/Reindex/components/CreateIndexFlyout/index.ts
  public/pages/Reindex/components/IndexSelect/IndexSelect.test.tsx
  public/pages/Reindex/components/IndexSelect/IndexSelect.tsx
  public/pages/Reindex/components/IndexSelect/__snapshots__/IndexSelect.test.tsx.snap
  public/pages/Reindex/components/IndexSelect/index.ts
  public/pages/Reindex/components/ReindexAdvancedOptions/ReindexAdvancedOptions.test.tsx
  public/pages/Reindex/components/ReindexAdvancedOptions/ReindexAdvancedOptions.tsx
  public/pages/Reindex/components/ReindexAdvancedOptions/__snapshots__/ReindexAdvancedOptions.test.tsx.snap
  public/pages/Reindex/components/ReindexAdvancedOptions/index.ts
  public/pages/Reindex/container/Reindex/Reindex.test.tsx
  public/pages/Reindex/container/Reindex/Reindex.tsx
  public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap
  public/pages/Reindex/container/Reindex/index.ts
  public/pages/Reindex/index.ts
  public/pages/Reindex/models/interfaces.ts
  public/pages/Reindex/utils/constants.ts
  public/services/IndexService.ts
  public/utils/constants.ts
  server/models/interfaces.ts
  server/plugin.ts
  server/routes/aliases.ts
  server/routes/index.ts
  server/services/AliasServices.ts
  server/services/index.ts
  utils/constants.ts
Labels: v2.5.0, index-operation

#412 Data stream selection popover auto adjust width
  public/app.scss
Labels: backport 2.x
