Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2022-10, with the labels that each got.

#261 Add rel to link for external links, IM dashboards plugin
  opensearch_dashboards.json
  package.json
  public/pages/ChangePolicy/components/NewPolicy/NewPolicy.tsx
  public/pages/CreatePolicy/components/DefinePolicy/DefinePolicy.tsx
  public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.tsx
  public/pages/CreateRollup/components/RollupIndices/RollupIndices.tsx
  public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx
  public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx
  public/pages/CreateTransform/components/TransformIndices/TransformIndices.tsx
  public/pages/Indices/components/ApplyPolicyModal/ApplyPolicyModal.tsx
  public/pages/Repositories/components/CreateRepositoryFlyout/CreateRepositoryFlyout.tsx
  public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
  public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
  public/pages/VisualCreatePolicy/components/ISMTemplates/ISMTemplates.tsx
  public/pages/VisualCreatePolicy/components/States/States.tsx
  public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
  public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.tsx
  public/pages/VisualCreatePolicy/containers/CreateTransition/CreateTransition.tsx
  public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.tsx
  public/pages/VisualCreatePolicy/containers/VisualCreatePolicy/VisualCreatePolicy.tsx
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.3.0.0.md
Labels: backport 2.x, backport 2.2

#283 Version increment 2.4
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  cypress/integration/rollups_spec.js
  opensearch_dashboards.json
  package.json
Labels: backport 2.x

#277 Add/update tests, update help text links and icons, add Restore activities panel
  cypress/integration/rollups_spec.js
  cypress/integration/snapshots_spec.js
  opensearch_dashboards.json
  package.json
  public/pages/Snapshots/components/AddPrefixInput/AddPrefixInput.test.tsx
  public/pages/Snapshots/components/AddPrefixInput/AddPrefixInput.tsx
  public/pages/Snapshots/components/AddPrefixInput/__snapshots__/AddPrefixInput.test.tsx.snap
  public/pages/Snapshots/components/IndexSettingsInput/IndexSettingsInput.tsx
  public/pages/Snapshots/components/IndexSettingsInput/index.ts
  public/pages/Snapshots/components/RenameInput/RenameInput.test.tsx
  public/pages/Snapshots/components/RenameInput/RenameInput.tsx
  public/pages/Snapshots/components/RenameInput/__snapshots__/RenameInput.test.tsx.snap
  public/pages/Snapshots/components/RestoreSnapshotFlyout/RestoreSnapshotFlyout.tsx
  public/pages/Snapshots/components/SnapshotIndicesInput/SnapshotIndicesInput.test.tsx
  public/pages/Snapshots/components/SnapshotIndicesInput/__snapshots__/SnapshotIndicesInput.test.tsx.snap
  public/pages/Snapshots/components/SnapshotRenameOptions/SnapshotRenameOptions.test.tsx
  public/pages/Snapshots/components/SnapshotRenameOptions/__snapshots__/SnapshotRenameOptions.test.tsx.snap
  public/pages/Snapshots/components/SnapshotRestoreAdvancedOptions/SnapshotRestoreAdvancedOptions.tsx
  public/pages/Snapshots/components/SnapshotRestoreOption/SnapshotRestoreOption.test.tsx
  public/pages/Snapshots/components/SnapshotRestoreOption/__snapshots__/SnapshotRestoreOption.test.tsx.snap
  public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
  server/models/interfaces.ts
Labels: backport 2.x

#294 Restore activities panel, monitoring restore progress, styling
  cypress.json
  cypress/integration/snapshots_spec.js
  cypress/support/commands.js
  public/pages/Snapshots/components/RestoreActivitiesPanel/RestoreActivitiesPanel.tsx
  public/pages/Snapshots/components/RestoreActivitiesPanel/index.ts
  public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
  public/services/SnapshotManagementService.ts
  public/utils/constants.ts
  server/models/interfaces.ts
  server/routes/snapshotManagement.ts
  server/services/SnapshotManagementService.ts
  utils/constants.ts
Labels: backport 2.x

#312 Feature/index detail
  cypress/integration/create_index.js
  cypress/integration/indices_spec.js
  models/interfaces.ts
  public/components/Modal/Modal.tsx
  public/pages/CreateIndex/components/AliasSelect/AliasSelect.test.tsx
  public/pages/CreateIndex/components/AliasSelect/__snapshots__/AliasSelect.test.tsx.snap
  public/pages/CreateIndex/components/AliasSelect/index.tsx
  public/pages/CreateIndex/components/IndexDetail/IndexDetail.test.tsx
  public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
  public/pages/CreateIndex/components/IndexDetail/__snapshots__/IndexDetail.test.tsx.snap
  public/pages/CreateIndex/components/IndexMapping/IndexMapping.test.tsx
  public/pages/CreateIndex/components/IndexMapping/IndexMapping.tsx
  public/pages/CreateIndex/components/IndexMapping/__snapshots__/IndexMapping.test.tsx.snap
  public/pages/CreateIndex/containers/AliasSelect/index.ts
  public/pages/CreateIndex/containers/CreateIndex/CreateIndex.test.tsx
  public/pages/CreateIndex/containers/CreateIndex/CreateIndex.tsx
  public/pages/CreateIndex/containers/CreateIndex/__snapshots__/CreateIndex.test.tsx.snap
  public/pages/Indices/components/IndexDetail/index.tsx
  public/pages/Indices/components/IndicesActions/index.tsx
  public/pages/Indices/containers/Indices/Indices.test.tsx
  public/pages/Indices/containers/Indices/Indices.tsx
  public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
  public/pages/Indices/utils/constants.tsx
  public/pages/Main/Main.tsx
  public/services/CommonService.ts
  public/utils/constants.ts
  server/models/interfaces.ts
  server/models/types.ts
  server/services/IndexService.ts
Labels: v2.5.0

#314 feat: enable inheritting from template function when creating index
  cypress/integration/create_index.js
  cypress/support/commands.js
  cypress/support/index.d.ts
  models/interfaces.ts
  public/pages/CreateIndex/components/AliasSelect/AliasSelect.test.tsx
  public/pages/CreateIndex/components/IndexDetail/IndexDetail.test.tsx
  public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
  public/pages/CreateIndex/containers/CreateIndex/CreateIndex.tsx
  public/pages/Indices/components/IndexDetail/index.tsx
Labels: v2.5.0
