Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2022-08, with the labels that each got.

#220 Updated rollup help text.
  public/pages/CreateRollup/components/RollupIndices/RollupIndices.tsx
  public/pages/CreateRollup/containers/CreateRollupForm/__snapshots__/CreateRollupForm.test.tsx.snap
Labels: backport 2.x

#218 Bumping 2.x branch from version 2.1 to 2.2.
  .github/workflows/cypress-workflow.yml
  opensearch_dashboards.json
  package.json
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.2.0.0.md
  yarn.lock
Labels: v2.2.0

#222 Added to 2.2 release notes.
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.2.0.0.md
Labels: v2.2.0, backport 2.2

#227 Bumping main to 2.2, address dependabot alert, enable test workflows on all PRs, fix snapshot tests.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  README.md
  opensearch_dashboards.json
  package.json
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.2.0.0.md
  test/setup.jest.ts
  yarn.lock
Labels: backport 2.x, backport 2.2

#229 Refactored dependency used by test mock. Adjusted OSD version used by test workflows.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  test/setup.jest.ts
Labels: backport 2.2

#230 Bumped moment version to resolve dependabot alert.
  package.json
  yarn.lock
Labels: backport 2.x

#239 [Backport 2.x] Version increment 2.2.1
  .github/workflows/cypress-workflow.yml
  opensearch_dashboards.json
  package.json
Labels: backport main

#236 Change alignment of Snapshot Management panels in pages/Main/Main.tsx
  cypress/integration/rollups_spec.js
  public/components/ContentPanel/ContentPanel.tsx
  public/components/ContentPanel/__snapshots__/ContentPanel.test.tsx.snap
  public/pages/ChangePolicy/components/ChangeManagedIndices/__snapshots__/ChangeManagedIndices.test.tsx.snap
  public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap
  public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
  public/pages/CreatePolicy/components/ConfigurePolicy/__snapshots__/ConfigurePolicy.test.tsx.snap
  public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap
  public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap
  public/pages/CreateRollup/containers/CreateRollupForm/__snapshots__/CreateRollupForm.test.tsx.snap
  public/pages/CreateTransform/containers/CreateTransformForm/__snapshots__/CreateTransformForm.test.tsx.snap
  public/pages/EditRollup/containers/__snapshots__/EditRollup.test.tsx.snap
  public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
  public/pages/Main/Main.tsx
  public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap
  public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap
  public/pages/PolicyDetails/components/PolicySettings/__snapshots__/PolicySettings.test.tsx.snap
  public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
  public/pages/Transforms/containers/Transforms/__snapshots__/EditTransform.test.tsx.snap
  public/pages/VisualCreatePolicy/components/ISMTemplates/__snapshots__/ISMTemplates.test.tsx.snap
  public/pages/VisualCreatePolicy/components/PolicyInfo/__snapshots__/PolicyInfo.test.tsx.snap
  public/pages/VisualCreatePolicy/components/States/__snapshots__/States.test.tsx.snap
  public/pages/VisualCreatePolicy/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap
Labels: backport 2.x
