Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2023-04, with the labels that each got.

#686 [BUG]Add downgrade logic when fetching indexes (#684)
  server/services/IndexService.ts
Labels: bug, roadmap

#606 Json validation new
  cypress/integration/plugins/index-management-dashboards-plugin/create_index.js
  package.json
  public/components/IndexDetail/IndexDetail.tsx
  public/components/IndexMapping/IndexMapping.tsx
  public/components/IndexMapping/helper.ts
  public/components/JSONDiffEditor/JSONDiffEditor.tsx
  public/components/JSONDiffEditor/interface.ts
  public/components/MonacoJSONEditor/MonacoJSONEditor.scss
  public/components/MonacoJSONEditor/MonacoJSONEditor.test.tsx
  public/components/MonacoJSONEditor/MonacoJSONEditor.tsx
  public/components/MonacoJSONEditor/__snapshots__/MonacoJSONEditor.test.tsx.snap
  public/components/MonacoJSONEditor/hooks.tsx
  public/components/MonacoJSONEditor/index.tsx
  public/components/MonacoJSONEditor/interface.ts
  public/components/SwitchableEditor/SwitchableEditor.tsx
  public/lib/monaco/index.ts
  public/lib/monaco/json.ts
  public/utils/JSON_schemas/index_mappings/index.ts
  public/utils/JSON_schemas/index_mappings/index_mappings.test.ts
  public/utils/JSON_schemas/index_mappings/property_item.ts
  public/utils/constants.ts
  yarn.lock
Labels: roadmap, backport main, v2.7.0, v2.x

#694 Add release note of 2.7
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.7.0.0.md
Labels: documentation, release, backport main, v2.7.0

#704 Fix: bugs during internal bugathon and fix the alias deletion issue in security mode.
  cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
  public/components/FormGenerator/built_in_components/index.tsx
  public/components/IndexDetail/IndexDetail.tsx
  public/components/IndexMapping/IndexMapping.tsx
  public/pages/Aliases/containers/AliasActions/AliasActions.test.tsx
  public/pages/Aliases/containers/AliasActions/index.tsx
  public/pages/Aliases/containers/DeleteAliasModal/DeleteAliasModal.tsx
  public/pages/CreateComposableTemplate/components/IndexSettings/IndexSettings.tsx
  public/pages/CreateIndex/containers/IndexForm/index.tsx
  public/pages/CreateIndexTemplate/components/IndexSettings/IndexSettings.tsx
  public/pages/CreateIndexTemplate/containers/ComposableTemplate/ComposableTemplate.tsx
  public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
  public/pages/IndexDetail/containers/IndexDetail/IndexDetail.tsx
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.7.0.0.md
  server/routes/indices.ts
  server/services/IndexService.ts
Labels: bug, backport main, v2.7.0

#708 Updated 2.7 release notes.
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7

#716 Common funcs for filter block indices
  public/utils/constants.ts
  public/utils/helpers.test.ts
  public/utils/helpers.ts
Labels: backport 2.x, v2.8.0

#718 Pass data stream to actions
  public/pages/CreateDataStream/containers/DataStreamDetail/DataStreamDetail.tsx
  public/pages/DataStreams/containers/DataStreams/DataStreams.tsx
  public/pages/DataStreams/containers/DataStreamsActions/DataStreamsActions.test.tsx
  public/pages/DataStreams/containers/DataStreamsActions/index.tsx
Labels: backport 2.x, v2.8.0
