Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2023-01, with the labels that each got.

#518 feat: fix mac platform error
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x

#561 2.5 release note
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5

#559 Minor changes for v2.5
  cypress/integration/create_index.js
  public/lib/field/rules/index.ts
  public/pages/Aliases/containers/CreateAlias/index.tsx
  public/pages/Aliases/containers/DeleteAliasModal/DeleteAliasModal.tsx
  public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
  public/pages/CreateIndex/components/IndexMapping/IndexMapping.tsx
  public/pages/CreateIndexTemplate/components/IndexSettings/IndexSettings.tsx
  public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/__snapshots__/CreateIndexTemplate.test.tsx.snap
  public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx
  public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx
  public/pages/Indices/components/CloseIndexModal/__snapshots__/CloseIndexModal.test.tsx.snap
  public/pages/Indices/components/DeleteIndexModal/DeleteIndexModal.test.tsx
  public/pages/Indices/components/DeleteIndexModal/DeleteIndexModal.tsx
  public/pages/Indices/components/DeleteIndexModal/__snapshots__/DeleteIndexModal.test.tsx.snap
  public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
Labels: backport main, backport 2.5

#567 Fix plugin version format
  .github/workflows/cypress-workflow.yml
  opensearch_dashboards.json
  package.json
Labels: backport 2.x, backport 2.5

#570 Remove inaccurate pre-check in shrink index page
  public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.test.tsx
  public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
Labels: backport 2.x, backport 2.5

#586 Fix CVE-2022-46175
  yarn.lock
Labels: backport 2.x, backport 2.5

#589 Reduce code conflicts
  cypress/integration/managed_indices_spec.js
  cypress/integration/policies_spec.js
  public/components/ContentPanel/ContentPanel.tsx
  public/components/ContentPanel/__snapshots__/ContentPanel.test.tsx.snap
  public/containers/IndexDetail/__snapshots__/IndexDetail.test.tsx.snap
  public/pages/ChangePolicy/components/ChangeManagedIndices/__snapshots__/ChangeManagedIndices.test.tsx.snap
  public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap
  public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
  public/pages/CreateIndex/components/IndexDetail/__snapshots__/IndexDetail.test.tsx.snap
  public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/__snapshots__/CreateIndexTemplate.test.tsx.snap
  public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
  public/pages/CreatePolicy/components/ConfigurePolicy/ConfigurePolicy.tsx
  public/pages/CreatePolicy/components/ConfigurePolicy/__snapshots__/ConfigurePolicy.test.tsx.snap
  public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap
  public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.test.tsx
  public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap
  public/pages/CreatePolicy/utils/constants.ts
  public/pages/CreateRollup/containers/CreateRollupForm/__snapshots__/CreateRollupForm.test.tsx.snap
  public/pages/CreateTransform/containers/CreateTransformForm/__snapshots__/CreateTransformForm.test.tsx.snap
  public/pages/EditRollup/containers/__snapshots__/EditRollup.test.tsx.snap
  public/pages/Indices/components/IndexControls/IndexControls.test.tsx
  public/pages/Indices/components/IndexControls/IndexControls.tsx
  public/pages/Indices/components/IndexControls/__snapshots__/IndexControls.test.tsx.snap
  public/pages/Indices/containers/Indices/Indices.tsx
  public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
  public/pages/Main/Main.tsx
  public/pages/ManagedIndices/components/ManagedIndexControls/ManagedIndexControls.test.tsx
  public/pages/ManagedIndices/components/ManagedIndexControls/ManagedIndexControls.tsx
  public/pages/ManagedIndices/components/ManagedIndexControls/__snapshots__/ManagedIndexControls.test.tsx.snap
  public/pages/ManagedIndices/containers/ManagedIndices/ManagedIndices.tsx
  public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap
  public/pages/Policies/components/PolicyControls/PolicyControls.test.tsx
  public/pages/Policies/components/PolicyControls/PolicyControls.tsx
  public/pages/Policies/components/PolicyControls/__snapshots__/PolicyControls.test.tsx.snap
  public/pages/Policies/containers/Policies/Policies.tsx
  public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap
  public/pages/PolicyDetails/components/PolicySettings/__snapshots__/PolicySettings.test.tsx.snap
  public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
  public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap
  public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap
  public/pages/Transforms/containers/Transforms/__snapshots__/EditTransform.test.tsx.snap
  public/pages/VisualCreatePolicy/components/PolicyInfo/__snapshots__/PolicyInfo.test.tsx.snap
  public/pages/VisualCreatePolicy/components/States/__snapshots__/States.test.tsx.snap
  public/utils/constants.ts
Labels: backport 2.x, backport 2.5
