Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2023-05, with the labels that each got.

#740 Add more wait time to make cypress tests pass
  .github/workflows/cypress-workflow.yml
Labels: infra, ci, v2.8.0

#737 Update path parameter to follow RFC/generic HTTP convention
  server/services/CommonService.ts
Labels: backport 2.x, backport main, backport 2.6, backport 2.7

#753 fix common funcs: status filter, empty response
  public/utils/helpers.test.ts
  public/utils/helpers.ts
Labels: backport 2.x

#713 add flush index UI to index operation
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  public/containers/FlushIndexModal/FlushIndexModal.test.tsx
  public/containers/FlushIndexModal/FlushIndexModal.tsx
  public/containers/FlushIndexModal/FlushIndexModalTestHelper.tsx
  public/containers/FlushIndexModal/__snapshots__/FlushIndexModal.test.tsx.snap
  public/containers/FlushIndexModal/index.ts
  public/pages/Aliases/containers/AliasActions/AliasActions.test.tsx
  public/pages/Aliases/containers/AliasActions/__snapshots__/AliasActions.test.tsx.snap
  public/pages/Aliases/containers/AliasActions/index.tsx
  public/pages/DataStreams/containers/DataStreamsActions/DataStreamsActions.test.tsx
  public/pages/DataStreams/containers/DataStreamsActions/__snapshots__/DataStreamsActions.test.tsx.snap
  public/pages/DataStreams/containers/DataStreamsActions/index.tsx
  public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
  public/pages/Indices/containers/IndicesActions/__snapshots__/IndicesActions.test.tsx.snap
  public/pages/Indices/containers/IndicesActions/index.tsx
Labels: feature, roadmap, backport 2.x, index-operation, v2.8.0

#730 Composable templates' backlog items in 2.8
  cypress/integration/plugins/index-management-dashboards-plugin/template_components.js
  public/components/ComponentTemplateBadge/ComponentTemplateBadge.tsx
  public/components/FilterGroup/FilterGroup.test.tsx
  public/components/FilterGroup/__snapshots__/FilterGroup.test.tsx.snap
  public/components/FilterGroup/index.tsx
  public/pages/ComposableTemplates/components/IndexControls/IndexControls.tsx
  public/pages/ComposableTemplates/components/IndexControls/__snapshots__/IndexControls.test.tsx.snap
  public/pages/ComposableTemplates/containers/AssociatedTemplatesModal/AssociatedTemplatesModal.test.tsx
  public/pages/ComposableTemplates/containers/AssociatedTemplatesModal/AssociatedTemplatesModal.tsx
  public/pages/ComposableTemplates/containers/AssociatedTemplatesModal/__snapshots__/AssociatedTemplatesModal.test.tsx.snap
  public/pages/ComposableTemplates/containers/ComposableTemplates/ComposableTemplates.test.tsx
  public/pages/ComposableTemplates/containers/ComposableTemplates/ComposableTemplates.tsx
  public/pages/ComposableTemplates/containers/ComposableTemplates/__snapshots__/ComposableTemplates.test.tsx.snap
  public/pages/ComposableTemplates/containers/ComposableTemplates/index.scss
  public/pages/ComposableTemplates/containers/ComposableTemplatesActions/ComposableTemplatesActions.test.tsx
  public/pages/ComposableTemplates/containers/ComposableTemplatesActions/__snapshots__/ComposableTemplatesActions.test.tsx.snap
  public/pages/ComposableTemplates/containers/ComposableTemplatesActions/index.tsx
  public/pages/ComposableTemplates/containers/DeleteComposableTemplatesModal/DeleteComposableTemplatesModal.test.tsx
  public/pages/ComposableTemplates/containers/DeleteComposableTemplatesModal/DeleteComposableTemplatesModal.tsx
  public/pages/ComposableTemplates/containers/DeleteComposableTemplatesModal/__snapshots__/DeleteComposableTemplatesModal.test.tsx.snap
  public/pages/ComposableTemplates/utils/hooks.tsx
  public/pages/ComposableTemplates/utils/services.ts
  public/pages/CreateComposableTemplate/containers/TemplateDetail/TemplateDetail.test.tsx
  public/pages/CreateComposableTemplate/containers/TemplateDetail/TemplateDetail.tsx
  public/pages/CreateComposableTemplate/hooks.tsx
  public/pages/CreateDataStream/containers/DataStreamDetail/hooks.tsx
  public/pages/CreateIndexTemplate/components/DefineTemplate/DefineTemplate.test.tsx
  public/pages/CreateIndexTemplate/components/DefineTemplate/DefineTemplate.tsx
  public/pages/CreateIndexTemplate/components/DefineTemplate/OverviewTemplate.tsx
  public/pages/CreateIndexTemplate/components/DefineTemplate/__snapshots__/DefineTemplate.test.tsx.snap
  public/pages/CreateIndexTemplate/components/DefineTemplate/index.ts
  public/pages/CreateIndexTemplate/containers/ComposableTemplate/ComposableTemplate.tsx
  public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/CreateIndexTemplate.test.tsx
  public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/__snapshots__/CreateIndexTemplate.test.tsx.snap
  public/pages/CreateIndexTemplate/containers/PreviewTemplate/PreviewTemplate.tsx
  public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.test.tsx
  public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx
  public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
  public/pages/CreateIndexTemplate/hooks.tsx
  public/pages/Templates/components/DeleteTemplate/index.tsx
  public/pages/Templates/containers/AssociatedComponentsModal/AssociatedComponentsModal.test.tsx
  public/pages/Templates/containers/AssociatedComponentsModal/AssociatedComponentsModal.tsx
  public/pages/Templates/containers/AssociatedComponentsModal/__snapshots__/AssociatedComponentsModal.test.tsx.snap
  public/pages/Templates/containers/Templates/IndexPatternDisplay.tsx
  public/pages/Templates/containers/Templates/Templates.tsx
  public/pages/Templates/containers/Templates/__snapshots__/Templates.test.tsx.snap
  public/pages/Templates/containers/Templates/index.scss
  test/mocks/index.ts
Labels: enhancement, feature, roadmap, backport 2.x, v2.8.0

#728 Add clear cache operation to indices, aliases and data streams pages
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  public/containers/ClearCacheModal/ClearCacheModal.test.tsx
  public/containers/ClearCacheModal/ClearCacheModal.tsx
  public/containers/ClearCacheModal/__snapshots__/ClearCacheModal.test.tsx.snap
  public/containers/ClearCacheModal/index.ts
  public/pages/Aliases/containers/AliasActions/AliasActions.test.tsx
  public/pages/Aliases/containers/AliasActions/__snapshots__/AliasActions.test.tsx.snap
  public/pages/Aliases/containers/AliasActions/index.tsx
  public/pages/DataStreams/containers/DataStreamsActions/DataStreamsActions.test.tsx
  public/pages/DataStreams/containers/DataStreamsActions/__snapshots__/DataStreamsActions.test.tsx.snap
  public/pages/DataStreams/containers/DataStreamsActions/index.tsx
  public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
  public/pages/Indices/containers/IndicesActions/__snapshots__/IndicesActions.test.tsx.snap
  public/pages/Indices/containers/IndicesActions/index.tsx
Labels: feature, roadmap, backport main, index-operation, v2.8.0

#761 Add refresh index as one of the index operations user can trigger fro…
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
  cypress/integration/plugins/index-management-dashboards-plugin/refresh_index.js
  public/containers/RefreshAction/index.tsx
  public/pages/Aliases/containers/AliasActions/AliasActions.test.tsx
  public/pages/Aliases/containers/AliasActions/__snapshots__/AliasActions.test.tsx.snap
  public/pages/Aliases/containers/AliasActions/index.tsx
  public/pages/DataStreams/containers/DataStreamsActions/DataStreamsActions.test.tsx
  public/pages/DataStreams/containers/DataStreamsActions/__snapshots__/DataStreamsActions.test.tsx.snap
  public/pages/DataStreams/containers/DataStreamsActions/index.tsx
  public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
  public/pages/Indices/containers/IndicesActions/__snapshots__/IndicesActions.test.tsx.snap
  public/pages/Indices/containers/IndicesActions/index.tsx
  test/setup.jest.ts
Labels: backport 2.x, index-operation, v2.8.0

#732 Side effects after taskable long running operation
  cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  public/JobHandler/callbacks/force_merge.test.tsx
  public/JobHandler/callbacks/force_merge.tsx
  public/JobHandler/callbacks/open.test.tsx
  public/JobHandler/callbacks/open.tsx
  public/JobHandler/callbacks/reindex.test.tsx
  public/JobHandler/callbacks/reindex.tsx
  public/JobHandler/callbacks/shrink.test.tsx
  public/JobHandler/callbacks/shrink.tsx
  public/JobHandler/callbacks/split.test.tsx
  public/JobHandler/callbacks/split.tsx
  public/JobHandler/components/DetailLink.tsx
  public/JobHandler/components/ErrorToastContentForJob.tsx
  public/JobHandler/components/FormatResourceWithClusterInfo.tsx
  public/JobHandler/components/__snapshots__/components.test.tsx.snap
  public/JobHandler/components/components.test.tsx
  public/JobHandler/index.ts
  public/JobHandler/interface.ts
  public/JobHandler/utils.ts
  public/lib/JobScheduler/JobScheduler.ts
  public/lib/JobScheduler/interface.ts
  public/lib/JobScheduler/store-localstorage.ts
  public/models/interfaces.ts
  public/pages/ForceMerge/container/ForceMerge/ForceMerge.tsx
  public/pages/IndexDetail/containers/IndexDetail/IndexDetail.tsx
  public/pages/Indices/containers/Indices/Indices.tsx
  public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
  public/pages/Indices/containers/IndicesActions/index.tsx
  public/pages/Indices/utils/helpers.ts
  public/pages/Reindex/container/Reindex/Reindex.tsx
  public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.test.tsx
  public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
  public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap
  public/pages/ShrinkIndex/utils/constants.ts
  public/pages/SplitIndex/components/SplitIndexForm/SplitIndexForm.tsx
  public/pages/SplitIndex/container/SplitIndex/SplitIndex.test.tsx
  public/pages/SplitIndex/container/SplitIndex/SplitIndex.tsx
  public/utils/helpers.ts
  test/mocks/coreServicesMock.ts
Labels: backport 2.x, index-operation, v2.8.0, notification

#754 Implemented alias action UX.
  cypress/fixtures/plugins/index-management-dashboards-plugin/sample_policy_alias_action.json
  cypress/integration/plugins/index-management-dashboards-plugin/policies_spec.js
  models/interfaces.ts
  public/containers/ErrorNotification/ErrorNotification.tsx
  public/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap
  public/pages/ChangePolicy/components/NewPolicy/NewPolicy.tsx
  public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap
  public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
  public/pages/CreatePolicy/components/DefinePolicy/DefinePolicy.tsx
  public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap
  public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.tsx
  public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap
  public/pages/CreatePolicy/utils/__snapshots__/helpers.test.tsx.snap
  public/pages/CreatePolicy/utils/helpers.test.tsx
  public/pages/CreatePolicy/utils/helpers.tsx
  public/pages/Indices/components/ApplyPolicyModal/ApplyPolicyModal.tsx
  public/pages/VisualCreatePolicy/components/ISMTemplates/ISMTemplates.tsx
  public/pages/VisualCreatePolicy/components/ISMTemplates/__snapshots__/ISMTemplates.test.tsx.snap
  public/pages/VisualCreatePolicy/components/States/States.tsx
  public/pages/VisualCreatePolicy/components/States/__snapshots__/States.test.tsx.snap
  public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
  public/pages/VisualCreatePolicy/components/UIActions/AliasUIAction/AliasUIAction.test.tsx
  public/pages/VisualCreatePolicy/components/UIActions/AliasUIAction/AliasUIAction.tsx
  public/pages/VisualCreatePolicy/components/UIActions/AliasUIAction/AliasUIActionComponent.tsx
  public/pages/VisualCreatePolicy/components/UIActions/AliasUIAction/__snapshots__/AliasUIAction.test.tsx.snap
  public/pages/VisualCreatePolicy/components/UIActions/index.ts
  public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.tsx
  public/pages/VisualCreatePolicy/containers/CreateAction/__snapshots__/CreateAction.test.tsx.snap
  public/pages/VisualCreatePolicy/containers/CreateTransition/CreateTransition.tsx
  public/pages/VisualCreatePolicy/containers/CreateTransition/__snapshots__/CreateTransition.test.tsx.snap
  public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.tsx
  public/pages/VisualCreatePolicy/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap
  public/pages/VisualCreatePolicy/containers/VisualCreatePolicy/VisualCreatePolicy.tsx
  public/pages/VisualCreatePolicy/utils/constants.ts
  public/pages/VisualCreatePolicy/utils/helpers.test.ts
  public/pages/VisualCreatePolicy/utils/helpers.ts
  public/utils/constants.ts
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md
Labels: backport 2.x, v2.8.0, backport 2.8

#779 Fix flush flaky test
  public/pages/Aliases/containers/AliasActions/AliasActions.test.tsx
  public/pages/Aliases/containers/AliasActions/__snapshots__/AliasActions.test.tsx.snap
  public/pages/DataStreams/containers/DataStreamsActions/DataStreamsActions.test.tsx
  public/pages/DataStreams/containers/DataStreamsActions/__snapshots__/DataStreamsActions.test.tsx.snap
  public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md
Labels: backport 2.x, v2.8.0, backport 2.8

#785 Fix CI on Node.js v18
  .github/workflows/cypress-workflow.yml
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md
Labels: infra, backport 2.x, v2.8.0, backport 2.8

#784 Wording changes
  public/containers/NotificationConfig/NotificationCallout.tsx
  public/containers/NotificationConfig/NotificationConfig.tsx
  public/containers/NotificationConfig/__snapshots__/NotificationCallout.test.tsx.snap
  public/containers/NotificationConfig/__snapshots__/NotificationConfig.test.tsx.snap
  public/pages/ForceMerge/container/ForceMerge/ForceMerge.tsx
  public/pages/ForceMerge/container/ForceMerge/__snapshots__/ForceMerge.test.tsx.snap
  public/pages/Notifications/constant.ts
  public/pages/Notifications/containers/Notifications/Notifications.tsx
  public/pages/Notifications/containers/Notifications/__snapshots__/Notifications.test.tsx.snap
  public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md
Labels: enhancement, backport 2.x, v2.8.0, backport 2.8
