Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2023-02, with the labels that each got.

#608 Feature: force merge
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  cypress/integration/force_merge.js
  opensearch_dashboards.json
  public/components/FormGenerator/built_in_components/index.tsx
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/ForceMergeAdvancedOptions.test.tsx
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/ForceMergeAdvancedOptions.tsx
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/__snapshots__/ForceMergeAdvancedOptions.test.tsx.snap
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/index.ts
  public/pages/ForceMerge/components/IndexSelect/IndexSelect.test.tsx
  public/pages/ForceMerge/components/IndexSelect/IndexSelect.tsx
  public/pages/ForceMerge/components/IndexSelect/__snapshots__/IndexSelect.test.tsx.snap
  public/pages/ForceMerge/components/IndexSelect/index.ts
  public/pages/ForceMerge/components/SwitchNumber/index.tsx
  public/pages/ForceMerge/container/ForceMerge/ForceMerge.test.tsx
  public/pages/ForceMerge/container/ForceMerge/ForceMerge.tsx
  public/pages/ForceMerge/container/ForceMerge/__snapshots__/ForceMerge.test.tsx.snap
  public/pages/ForceMerge/container/ForceMerge/index.ts
  public/pages/ForceMerge/index.ts
  public/pages/ForceMerge/models/interfaces.ts
  public/pages/ForceMerge/utils/constants.ts
  public/pages/ForceMerge/utils/helper.test.ts
  public/pages/ForceMerge/utils/helper.ts
  public/pages/Indices/containers/IndicesActions/index.tsx
  public/pages/Main/Main.tsx
  public/utils/constants.ts
Labels: backport main, v2.x

#631 Drafted 2.6 release notes.
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.6.0.0.md
Labels: backport 2.x

#605 Feature: data streams
  cypress/integration/data_streams.js
  public/components/DescriptionListHoz/DescriptionListHoz.tsx
  public/components/FormGenerator/built_in_components/index.tsx
  public/pages/CreateDataStream/components/IndexSettings/IndexSettings.tsx
  public/pages/CreateDataStream/containers/BackingIndices/BackingIndices.tsx
  public/pages/CreateDataStream/containers/CreateDataStream/__snapshots__/CreateDataStream.test.tsx.snap
  public/pages/CreateDataStream/containers/DataStreamDetail/DataStreamDetail.tsx
  public/pages/CreateDataStream/containers/DataStreamDetail/__snapshots__/DataStreamDetail.test.tsx.snap
  public/pages/CreateDataStream/containers/DefineDataStream/DefineDataStream.tsx
  public/pages/CreateDataStream/containers/IndexAlias/IndexAlias.tsx
  public/pages/CreateDataStream/containers/TemplateMappings/TemplateMappings.tsx
  public/pages/CreateDataStream/hooks.tsx
  public/pages/CreateDataStream/interface.ts
  public/pages/CreateIndexTemplate/components/DefineTemplate/DefineTemplate.tsx
  public/pages/CreateIndexTemplate/components/TemplateType/TemplateType.tsx
  public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/CreateIndexTemplate.tsx
  public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.test.tsx
  public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx
  public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
  public/pages/DataStreams/containers/DataStreams/DataStreams.tsx
  public/pages/DataStreams/containers/DataStreams/__snapshots__/DataStreams.test.tsx.snap
  public/pages/DataStreams/containers/DeleteDataStreamsModal/DeleteDataStreamsModal.tsx
  public/pages/DataStreams/containers/DeleteDataStreamsModal/__snapshots__/DeleteDataStreamsModal.test.tsx.snap
  public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
  public/pages/Indices/utils/constants.tsx
Labels: backport main, v2.6.0, v2.x, backport 2.6

#634 [Backport main]Feature: force merge (#608)
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  cypress/integration/force_merge.js
  public/components/FormGenerator/built_in_components/index.tsx
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/ForceMergeAdvancedOptions.test.tsx
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/ForceMergeAdvancedOptions.tsx
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/__snapshots__/ForceMergeAdvancedOptions.test.tsx.snap
  public/pages/ForceMerge/components/ForceMergeAdvancedOptions/index.ts
  public/pages/ForceMerge/components/IndexSelect/IndexSelect.test.tsx
  public/pages/ForceMerge/components/IndexSelect/IndexSelect.tsx
  public/pages/ForceMerge/components/IndexSelect/__snapshots__/IndexSelect.test.tsx.snap
  public/pages/ForceMerge/components/IndexSelect/index.ts
  public/pages/ForceMerge/components/SwitchNumber/index.tsx
  public/pages/ForceMerge/container/ForceMerge/ForceMerge.test.tsx
  public/pages/ForceMerge/container/ForceMerge/ForceMerge.tsx
  public/pages/ForceMerge/container/ForceMerge/__snapshots__/ForceMerge.test.tsx.snap
  public/pages/ForceMerge/container/ForceMerge/index.ts
  public/pages/ForceMerge/index.ts
  public/pages/ForceMerge/models/interfaces.ts
  public/pages/ForceMerge/utils/constants.ts
  public/pages/ForceMerge/utils/helper.test.ts
  public/pages/ForceMerge/utils/helper.ts
  public/pages/Indices/containers/IndicesActions/index.tsx
  public/pages/Main/Main.tsx
  public/utils/constants.ts
Labels: backport 2.6

#641 Fix Node.js and Yarn installation in CI
  .github/workflows/cypress-workflow.yml
  .github/workflows/release-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x, backport 2.6

#632 2.6 release note
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.6.0.0.md
Labels: backport 2.x, v2.6.0, backport 2.6
