Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2023-03, with the labels that each got.

#663 Refractor/e2e test to FTRepo
  cypress.json
  cypress/fixtures/plugins/index-management-dashboards-plugin/sample_data_stream_policy.json
  cypress/fixtures/plugins/index-management-dashboards-plugin/sample_policy.json
  cypress/fixtures/plugins/index-management-dashboards-plugin/sample_rollover_policy.json
  cypress/fixtures/plugins/index-management-dashboards-plugin/sample_rollup.json
  cypress/fixtures/plugins/index-management-dashboards-plugin/sample_transform.json
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/create_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
  cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/policies_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/reindex_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/rollover.js
  cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/split_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/templates.js
  cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
  cypress/support/commands.js
  cypress/support/constants.js
  cypress/support/index.d.ts
  cypress/support/index.js
  cypress/utils/base_constants.js
  cypress/utils/commands.js
  cypress/utils/constants.js
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
  cypress/utils/plugins/index-management-dashboards-plugin/constants.js
Labels: infra, backport main, v2.7.0

#684 [BUG]Add downgrade logic when fetching indexes
  .github/workflows/cypress-workflow.yml
  server/services/IndexService.ts
Labels: bug, backport main, v2.7.0

#652 Update broken link
  public/pages/CreateRollup/components/AdvancedAggregation/AdvancedAggregation.tsx
Labels: bug, backport 2.x, v2.7.0
