Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2023-07, with the labels that each got.

#801 fix: add validation on data.method when using transport.request
  server/services/CommonService.test.ts
  server/services/CommonService.ts
Labels: bug, backport 2.x, v2.9.0

#741 Move index management from plugin section to management section
  .eslintrc.js
  opensearch_dashboards.json
  package.json
  public/pages/Main/Main.tsx
  public/plugin.ts
Labels: backport 2.x, 2.9.0

#808 Added 2.9 release notes.
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#813 Bumped tough-cookie, and semver versions.
  package.json
  yarn.lock
Labels: backport 2.9

#821 Upgrade the backport workflow
  .github/workflows/backport.yml
Labels: backport 2.x

#824 Fixed repo name in snapshot flyout; Use schedule from policy during edit
  public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx
  public/pages/Snapshots/components/SnapshotFlyout/SnapshotFlyout.tsx
Labels: backport 2.x
