Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2024-03, with the labels that each got.

#993 rollups/transform: wait for page to render
  cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Labels: backport 2.x, v2.12.0, backport 2.12

#1001 Fixed CVEs for OS 1.3.15 patch release
  package.json
  yarn.lock
Labels: backport 1.x, backport 2.x

#999 Add workflow to verify binary installation into dashboards core
  .github/workflows/verify-binary-installation.yml
Labels: backport 2.x
