Repository opensearch-project/index-management-dashboards-plugin, pull requests merged in 2024-07, with the labels that each got.

#1080 Adding dataVersionFilter support to MDS to enable version decoupling
  opensearch_dashboards.json
  public/pages/Main/Main.tsx
Labels: backport 2.x

#1085 New Navigation UX change
  public/pages/Main/Main.tsx
  public/plugin.ts
  yarn.lock
Labels: backport 2.x, v2.16.0

#1084 Add MDS support to snapshot pages
  public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx
  public/pages/Main/Main.tsx
  public/pages/Repositories/components/CreateRepositoryFlyout/CreateRepositoryFlyout.tsx
  public/pages/Repositories/containers/Repositories/Repositories.tsx
  public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
  public/pages/SnapshotPolicyDetails/containers/SnapshotPolicyDetails/SnapshotPolicyDetails.tsx
  public/pages/Snapshots/components/CreateSnapshotFlyout/CreateSnapshotFlyout.tsx
  public/pages/Snapshots/components/RestoreSnapshotFlyout/RestoreSnapshotFlyout.tsx
  public/pages/Snapshots/components/SnapshotFlyout/SnapshotFlyout.tsx
  public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
  public/services/SnapshotManagementService.ts
  server/plugin.ts
  server/routes/snapshotManagement.ts
  server/services/SnapshotManagementService.ts
Labels: backport 2.x, v2.16.0

#1088 Persist dataSourceId across applications under new Nav change
  public/pages/Main/Main.tsx
  public/plugin.ts
Labels: backport 2.x

#1094 [navigation]feat: reuse applications
  public/plugin.ts
Labels: backport 2.x, v2.16.0

#1096 feat: reuse applications (#1094)
  public/plugin.ts
Labels: v2.16.0, backport 2.16

#1099 Added release notes for v2.16
  release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16
